
# 服务配置
Server:
  RunMode: debug # debug or release
  HttpPort: 8088 
  ReadTimeout: 60 
  WriteTimeout: 60 
# 应用配置
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  # 上传相关配置
  Upload:
    # 图片上传配置
    UploadSavePath: storage/uploads
    UploadServerUrl: http://127.0.0.1:8088/static
    UploadImageMaxSize: 5 # MB
    UploadImageAllowExts:
      - .jpg
      - .jpeg
      - .png
      - .gif
JWT:
  Secret: eddycjy
  Issuer: blog-service
  Expire: 7200  # 以秒为单位，7200秒即2小时

# 数据库配置
Database:
  DBType: mysql
  Username: root  # 填写你的数据库账号
  Password: 123456  # 填写你的数据库密码
  Host: 127.0.0.1:3306
  DBName: blog_service
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30

